# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('energy-module-lte-example', ['energy-module-lte'])
    obj.source = 'energy-module-lte-example.cc'

